# Generated by Django 5.0 on 2023-12-26 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffe',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
