# Generated by Django 5.0 on 2023-12-26 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_coffe_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffe',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
